---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: git-assets
- name: app-colour

outputs:
- name: app-services

run:
  path: git-assets/pipeline/scripts/app-services.sh
  
  