platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: branch-dev
outputs:
  - name: mvn-package-output

run:
  path: "mvn"
  args: ["-f", "pom.xml", "package"]
