resources:
- name: git-assets
  type: git
  source:
    uri: https://github.com/mattsday/spring-boot-pcf-demo
    branch: master
    
- name: release
  type: s3
  source:
    bucket: ((aws-bucket-name))
    region_name: ((aws-region-name))
    regexp: ((aws-regexp))
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-key))
    
- name: PCF
  type: cf
  source:
    api: ((pcf-api))
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-org))
    space: ((pcf-space))
    skip_cert_check: false
    
jobs:
- name: build-artifact
  serial: true
  plan:
  - get: git-assets
    trigger: true
  - task: mvn-package
    privileged: true
    file: git-assets/pipeline/package.yml
  - put: release
    params:
      file: mvn-package-output/demo-0.0.1-SNAPSHOT.jar
      acl: public-read
      
- name: deploy-app
  serial: true
  public: true
  plan:
  - get: git-assets
    trigger: true
    passed:
    - build-artifact
  - get: release
    trigger: true
    passed:
    - build-artifact
  - task: get-current-app-color
    file: git-assets/pipeline/app-colour.yml
    params:
      CF_APP: demo-mday
      CF_APP_DOMAIN: ((cf-app-domain))
      CF_API: ((pcf-api))
      CF_ORG: ((pcf-org))
      CF_USER: ((pcf-username))
      CF_PWD: ((pcf-password))
      CF_SPACE: ((pcf-space))
  - task: generate-manifest
    file: git-assets/pipeline/generate-manifest.yml
    params:
      APP_PACKAGE: ../release/demo-0.0.1-SNAPSHOT.jar
  - put: PCF
    params:
      manifest: manifest-output/manifest.yml

    